### ISSUE TITLE
Nice work! You can remove sessions on TFMobileNetSSDFaceDetector with dynamic programming (PyTorch)

### ISSUE THREAD

**Issue by rchavezj** [muratcancicek/Head_Based_Interaction#1]
I see you are using tensorflow 1.0 to train your models on TFMobileNetSSDFaceDetector. If you're interested, the CEO of OpenCV has created a computer vision course with the integration of PyTorch ( https://opencv.org/courses/ ) to deploy your cv algorithms either in python or c++.

**Comment by muratcancicek** [comment]
@rchavezj Thank you so much for your interest in the project and the advice. I am planning to add also PyTorch implementation of the FaceDetector. I have just started a full-time research internship and you may guess how busy I am right now. 

By the way, don't forget it's an open-source project! You may also add PyTorch version of detectors if would like. It would be really appreciated.

**Comment by rchavezj** [comment]
After I finish the OpenCV & PyTorch course, I'll see if I can come back to your project.

**Comment by rchavezj** [comment]
After I finish the OpenCV & PyTorch course, I'll see if I can come back to your project.
